# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.license_deactivate import LicenseDeactivate


class TestLicenseDeactivate(unittest.TestCase):
    """ LicenseDeactivate unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLicenseDeactivate(self):
        """
        Test LicenseDeactivate
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.license_deactivate.LicenseDeactivate()
        pass


if __name__ == '__main__':
    unittest.main()
