# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.datastore import Datastore


class TestDatastore(unittest.TestCase):
    """ Datastore unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatastore(self):
        """
        Test Datastore
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.datastore.Datastore()
        pass


if __name__ == '__main__':
    unittest.main()
