# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.vidm_user_request import VidmUserRequest


class TestVidmUserRequest(unittest.TestCase):
    """ VidmUserRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVidmUserRequest(self):
        """
        Test VidmUserRequest
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.vidm_user_request.VidmUserRequest()
        pass


if __name__ == '__main__':
    unittest.main()
