# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.nsxt_load_balancer import NSXTLoadBalancer


class TestNSXTLoadBalancer(unittest.TestCase):
    """ NSXTLoadBalancer unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNSXTLoadBalancer(self):
        """
        Test NSXTLoadBalancer
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.nsxt_load_balancer.NSXTLoadBalancer()
        pass


if __name__ == '__main__':
    unittest.main()
