# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.f5_bigip_data_source_request import F5BIGIPDataSourceRequest


class TestF5BIGIPDataSourceRequest(unittest.TestCase):
    """ F5BIGIPDataSourceRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testF5BIGIPDataSourceRequest(self):
        """
        Test F5BIGIPDataSourceRequest
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.f5_bigip_data_source_request.F5BIGIPDataSourceRequest()
        pass


if __name__ == '__main__':
    unittest.main()
