# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.aggregation_response import AggregationResponse


class TestAggregationResponse(unittest.TestCase):
    """ AggregationResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggregationResponse(self):
        """
        Test AggregationResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.aggregation_response.AggregationResponse()
        pass


if __name__ == '__main__':
    unittest.main()
