# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.aws_credentials import AWSCredentials


class TestAWSCredentials(unittest.TestCase):
    """ AWSCredentials unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAWSCredentials(self):
        """
        Test AWSCredentials
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.aws_credentials.AWSCredentials()
        pass


if __name__ == '__main__':
    unittest.main()
