# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.snmp_destination_collector_mapping import SnmpDestinationCollectorMapping


class TestSnmpDestinationCollectorMapping(unittest.TestCase):
    """ SnmpDestinationCollectorMapping unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnmpDestinationCollectorMapping(self):
        """
        Test SnmpDestinationCollectorMapping
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.snmp_destination_collector_mapping.SnmpDestinationCollectorMapping()
        pass


if __name__ == '__main__':
    unittest.main()
