# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""




import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.k8_s_credentials import K8SCredentials


class TestK8SCredentials(unittest.TestCase):
    """ K8SCredentials unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testK8SCredentials(self):
        """
        Test K8SCredentials
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.k8_s_credentials.K8SCredentials()
        pass


if __name__ == '__main__':
    unittest.main()
