# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.policy_manager_segment import PolicyManagerSegment


class TestPolicyManagerSegment(unittest.TestCase):
    """ PolicyManagerSegment unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyManagerSegment(self):
        """
        Test PolicyManagerSegment
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.policy_manager_segment.PolicyManagerSegment()
        pass


if __name__ == '__main__':
    unittest.main()
