# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.dell_os10_switch_data_source_request import DellOs10SwitchDataSourceRequest


class TestDellOs10SwitchDataSourceRequest(unittest.TestCase):
    """ DellOs10SwitchDataSourceRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDellOs10SwitchDataSourceRequest(self):
        """
        Test DellOs10SwitchDataSourceRequest
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.dell_os10_switch_data_source_request.DellOs10SwitchDataSourceRequest()
        pass


if __name__ == '__main__':
    unittest.main()
