# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.data_source_type import DataSourceType


class TestDataSourceType(unittest.TestCase):
    """ DataSourceType unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataSourceType(self):
        """
        Test DataSourceType
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.data_source_type.DataSourceType()
        pass


if __name__ == '__main__':
    unittest.main()
