# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.ip_sec_vpn_session import IPSecVPNSession


class TestIPSecVPNSession(unittest.TestCase):
    """ IPSecVPNSession unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIPSecVPNSession(self):
        """
        Test IPSecVPNSession
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.ip_sec_vpn_session.IPSecVPNSession()
        pass


if __name__ == '__main__':
    unittest.main()
