# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.data_sources_api import DataSourcesApi


class TestDataSourcesApi(unittest.TestCase):
    """ DataSourcesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.data_sources_api.DataSourcesApi()

    def tearDown(self):
        pass

    def test_add_arista_switch(self):
        """
        Test case for add_arista_switch

        Create an arista switch data source
        """
        pass

    def test_add_aws_datasource(self):
        """
        Test case for add_aws_datasource

        Create an AWS data source
        """
        pass

    def test_add_azure_datasource(self):
        """
        Test case for add_azure_datasource

        Create an azure data source
        """
        pass

    def test_add_brocade_switch(self):
        """
        Test case for add_brocade_switch

        Create a brocade switch data source
        """
        pass

    def test_add_checkpoint_firewall(self):
        """
        Test case for add_checkpoint_firewall

        Create a checkpoint firewall
        """
        pass

    def test_add_cisco_aci(self):
        """
        Test case for add_cisco_aci

        Create a Cisco ACI data source
        """
        pass

    def test_add_cisco_asrxr_switch(self):
        """
        Test case for add_cisco_asrxr_switch

        Create a Cisco ASRXR switch as data source
        """
        pass

    def test_add_cisco_switch(self):
        """
        Test case for add_cisco_switch

        Create a cisco switch data source
        """
        pass

    def test_add_dell_os10_switch(self):
        """
        Test case for add_dell_os10_switch

        Create a dell OS10 switch data source
        """
        pass

    def test_add_dell_switch(self):
        """
        Test case for add_dell_switch

        Create a dell switch data source
        """
        pass

    def test_add_f5_bigip(self):
        """
        Test case for add_f5_bigip

        Add a F5 BIG-IP as data source
        """
        pass

    def test_add_fortinet_firewall(self):
        """
        Test case for add_fortinet_firewall

        Add Fortinet firewall as data source
        """
        pass

    def test_add_generic_switch(self):
        """
        Test case for add_generic_switch

        Create generic switch as data source
        """
        pass

    def test_add_hcx_datasource(self):
        """
        Test case for add_hcx_datasource

        Create an hcx data source
        """
        pass

    def test_add_hpe_switch(self):
        """
        Test case for add_hpe_switch

        Create a HPE switch as data source
        """
        pass

    def test_add_hpov_manager(self):
        """
        Test case for add_hpov_manager

        Create a hp oneview manager data source
        """
        pass

    def test_add_hpvc_manager(self):
        """
        Test case for add_hpvc_manager

        Create a hpvc manager data source
        """
        pass

    def test_add_huawei(self):
        """
        Test case for add_huawei

        Add a Huawei as data source
        """
        pass

    def test_add_infoblox_manager_datasource(self):
        """
        Test case for add_infoblox_manager_datasource

        Create an infoblox manager data source
        """
        pass

    def test_add_juniper_switch(self):
        """
        Test case for add_juniper_switch

        Add a juniper switch as data source
        """
        pass

    def test_add_kubernetes_datasource(self):
        """
        Test case for add_kubernetes_datasource

        Create an kubernetes cluster data source
        """
        pass

    def test_add_mellanox_switch(self):
        """
        Test case for add_mellanox_switch

        Create a Mellanox switch as data source
        """
        pass

    def test_add_nsxalb_datasource(self):
        """
        Test case for add_nsxalb_datasource

        Create an NSX-ALB data source
        """
        pass

    def test_add_nsxt_manager_datasource(self):
        """
        Test case for add_nsxt_manager_datasource

        Create an nsx-t manager data source
        """
        pass

    def test_add_nsxv_manager_datasource(self):
        """
        Test case for add_nsxv_manager_datasource

        Create an nsx-v manager data source
        """
        pass

    def test_add_openshift_datasource(self):
        """
        Test case for add_openshift_datasource

        Create an Openshift data source
        """
        pass

    def test_add_panorama_firewall(self):
        """
        Test case for add_panorama_firewall

        Create panorama firewall data source
        """
        pass

    def test_add_pks_datasource(self):
        """
        Test case for add_pks_datasource

        Create an pks data source
        """
        pass

    def test_add_policy_manager_datasource(self):
        """
        Test case for add_policy_manager_datasource

        Create a vmc nsx manager data source
        """
        pass

    def test_add_service_now_datasource(self):
        """
        Test case for add_service_now_datasource

        Create an ServiceNow instance data source
        """
        pass

    def test_add_ucs_manager(self):
        """
        Test case for add_ucs_manager

        Create a ucs manager data source
        """
        pass

    def test_add_vcenter_datasource(self):
        """
        Test case for add_vcenter_datasource

        Create a vCenter data source
        """
        pass

    def test_add_velo_cloud_datasource(self):
        """
        Test case for add_velo_cloud_datasource

        Create a velocloud data source
        """
        pass

    def test_delete_arista_switch(self):
        """
        Test case for delete_arista_switch

        Delete an arista switch data source
        """
        pass

    def test_delete_aws_data_source(self):
        """
        Test case for delete_aws_data_source

        Delete an AWS data source
        """
        pass

    def test_delete_azure_subscription(self):
        """
        Test case for delete_azure_subscription

        Delete an azure data source
        """
        pass

    def test_delete_brocade_switch(self):
        """
        Test case for delete_brocade_switch

        Delete a brocade switch data source
        """
        pass

    def test_delete_checkpoint_firewall(self):
        """
        Test case for delete_checkpoint_firewall

        Delete a checkpoint firewall data source
        """
        pass

    def test_delete_cisco_aci(self):
        """
        Test case for delete_cisco_aci

        Delete a Cisco ACI data source
        """
        pass

    def test_delete_cisco_asrxr_switch(self):
        """
        Test case for delete_cisco_asrxr_switch

        Delete a Cisco ASRXR switch data source
        """
        pass

    def test_delete_cisco_switch(self):
        """
        Test case for delete_cisco_switch

        Delete a cisco switch data source
        """
        pass

    def test_delete_dell_os10_switch(self):
        """
        Test case for delete_dell_os10_switch

        Delete a dell os10 switch data source
        """
        pass

    def test_delete_dell_switch(self):
        """
        Test case for delete_dell_switch

        Delete a dell switch data source
        """
        pass

    def test_delete_f5_bigip(self):
        """
        Test case for delete_f5_bigip

        Delete a F5 BIG-IP data source
        """
        pass

    def test_delete_fortinet_firewall(self):
        """
        Test case for delete_fortinet_firewall

        Delete a Fortinet firewall data source
        """
        pass

    def test_delete_generic_switch(self):
        """
        Test case for delete_generic_switch

        Delete generic switch data source
        """
        pass

    def test_delete_hcx(self):
        """
        Test case for delete_hcx

        Delete an hcx data source
        """
        pass

    def test_delete_hpe_switch(self):
        """
        Test case for delete_hpe_switch

        Delete a HPE switch data source
        """
        pass

    def test_delete_hpov_manager(self):
        """
        Test case for delete_hpov_manager

        Delete a hp oneview data source
        """
        pass

    def test_delete_hpvc_manager(self):
        """
        Test case for delete_hpvc_manager

        Delete a hpvc manager data source
        """
        pass

    def test_delete_huawei(self):
        """
        Test case for delete_huawei

        Delete a Huawei data source
        """
        pass

    def test_delete_infoblox_manager(self):
        """
        Test case for delete_infoblox_manager

        Delete an infoblox manager data source
        """
        pass

    def test_delete_juniper_switch(self):
        """
        Test case for delete_juniper_switch

        Delete a juniper switch data source
        """
        pass

    def test_delete_kubernetes_cluster(self):
        """
        Test case for delete_kubernetes_cluster

        Delete an kubernetes cluster data source
        """
        pass

    def test_delete_mellanox_switch(self):
        """
        Test case for delete_mellanox_switch

        Delete a Mellanox switch data source
        """
        pass

    def test_delete_nsxalb(self):
        """
        Test case for delete_nsxalb

        Delete an NSX-ALB data source
        """
        pass

    def test_delete_nsxt_manager(self):
        """
        Test case for delete_nsxt_manager

        Delete an nsx-t manager data source
        """
        pass

    def test_delete_nsxv_manager(self):
        """
        Test case for delete_nsxv_manager

        Delete an nsx-v manager data source
        """
        pass

    def test_delete_openshift_cluster(self):
        """
        Test case for delete_openshift_cluster

        Delete an openshift data source
        """
        pass

    def test_delete_panorama_firewall(self):
        """
        Test case for delete_panorama_firewall

        Delete a panorama firewall data source
        """
        pass

    def test_delete_pks(self):
        """
        Test case for delete_pks

        Delete an pks data source
        """
        pass

    def test_delete_policy_manager(self):
        """
        Test case for delete_policy_manager

        Delete a vmc nsx manager data source
        """
        pass

    def test_delete_service_now_instance(self):
        """
        Test case for delete_service_now_instance

        Delete an ServiceNow instance data source
        """
        pass

    def test_delete_ucs_manager(self):
        """
        Test case for delete_ucs_manager

        Delete a ucs manager data source
        """
        pass

    def test_delete_vcenter(self):
        """
        Test case for delete_vcenter

        Delete a vCenter data source
        """
        pass

    def test_delete_velo_cloud(self):
        """
        Test case for delete_velo_cloud

        Delete a velocloud data source
        """
        pass

    def test_disable_arista_switch(self):
        """
        Test case for disable_arista_switch

        Disable an arista switch data source
        """
        pass

    def test_disable_aws_data_source(self):
        """
        Test case for disable_aws_data_source

        Disable an AWS data source
        """
        pass

    def test_disable_azure_subscription(self):
        """
        Test case for disable_azure_subscription

        Disable an azure data source
        """
        pass

    def test_disable_brocade_switch(self):
        """
        Test case for disable_brocade_switch

        Disable a brocade switch data source
        """
        pass

    def test_disable_checkpoint_firewall(self):
        """
        Test case for disable_checkpoint_firewall

        Disable a checkpoint firewall data source
        """
        pass

    def test_disable_cisco_aci(self):
        """
        Test case for disable_cisco_aci

        Disable a Cisco ACI data source
        """
        pass

    def test_disable_cisco_asrxr_switch(self):
        """
        Test case for disable_cisco_asrxr_switch

        Disable a Cisco ASRXR switch data source
        """
        pass

    def test_disable_cisco_switch(self):
        """
        Test case for disable_cisco_switch

        Disable a cisco switch data source
        """
        pass

    def test_disable_dell_os10_switch(self):
        """
        Test case for disable_dell_os10_switch

        Disable a dell os10 switch data source
        """
        pass

    def test_disable_dell_switch(self):
        """
        Test case for disable_dell_switch

        Disable a dell switch data source
        """
        pass

    def test_disable_f5_bigip(self):
        """
        Test case for disable_f5_bigip

        Disable a F5 BIG-IP data source
        """
        pass

    def test_disable_fortinet_firewall(self):
        """
        Test case for disable_fortinet_firewall

        Disable a Fortinet firewall data source
        """
        pass

    def test_disable_generic_switch(self):
        """
        Test case for disable_generic_switch

        Disable generic switch data source
        """
        pass

    def test_disable_hcx(self):
        """
        Test case for disable_hcx

        Disable an hcx data source
        """
        pass

    def test_disable_hpe_switch(self):
        """
        Test case for disable_hpe_switch

        Disable a HPE switch data source
        """
        pass

    def test_disable_hpov_manager(self):
        """
        Test case for disable_hpov_manager

        Disable a hp oneview data source
        """
        pass

    def test_disable_hpvc_manager(self):
        """
        Test case for disable_hpvc_manager

        Disable a hpvc manager data source
        """
        pass

    def test_disable_huawei(self):
        """
        Test case for disable_huawei

        Disable a Huawei data source
        """
        pass

    def test_disable_infoblox_manager(self):
        """
        Test case for disable_infoblox_manager

        Disable an infoblox manager data source
        """
        pass

    def test_disable_juniper_switch(self):
        """
        Test case for disable_juniper_switch

        Disable a juniper switch data source
        """
        pass

    def test_disable_kubernetes_cluster(self):
        """
        Test case for disable_kubernetes_cluster

        Disable an kubernetes cluster data source
        """
        pass

    def test_disable_mellanox_switch(self):
        """
        Test case for disable_mellanox_switch

        Disable a Mellanox switch data source
        """
        pass

    def test_disable_nsxalb(self):
        """
        Test case for disable_nsxalb

        Disable an NSX-ALB data source
        """
        pass

    def test_disable_nsxt_manager(self):
        """
        Test case for disable_nsxt_manager

        Disable an nsx-t manager data source
        """
        pass

    def test_disable_nsxv_manager(self):
        """
        Test case for disable_nsxv_manager

        Disable an nsx-v manager data source
        """
        pass

    def test_disable_openshift_cluster(self):
        """
        Test case for disable_openshift_cluster

        Disable an openshift data source
        """
        pass

    def test_disable_panorama_firewall(self):
        """
        Test case for disable_panorama_firewall

        Disable a panorama firewall data source
        """
        pass

    def test_disable_pks(self):
        """
        Test case for disable_pks

        Disable an pks data source
        """
        pass

    def test_disable_policy_manager(self):
        """
        Test case for disable_policy_manager

        Disable a vmc nsx manager data source
        """
        pass

    def test_disable_service_now_instance(self):
        """
        Test case for disable_service_now_instance

        Disable an ServiceNow instance data source
        """
        pass

    def test_disable_ucs_manager(self):
        """
        Test case for disable_ucs_manager

        Disable a ucs manager data source
        """
        pass

    def test_disable_vcenter(self):
        """
        Test case for disable_vcenter

        Disable a vCenter data source
        """
        pass

    def test_disable_velo_cloud(self):
        """
        Test case for disable_velo_cloud

        Disable a velocloud data source
        """
        pass

    def test_enable_arista_switch(self):
        """
        Test case for enable_arista_switch

        Enable an arista switch data source
        """
        pass

    def test_enable_aws_data_source(self):
        """
        Test case for enable_aws_data_source

        Enable an AWS data source
        """
        pass

    def test_enable_azure_subscription(self):
        """
        Test case for enable_azure_subscription

        Enable an azure data source
        """
        pass

    def test_enable_brocade_switch(self):
        """
        Test case for enable_brocade_switch

        Enable a brocade switch data source
        """
        pass

    def test_enable_checkpoint_firewall(self):
        """
        Test case for enable_checkpoint_firewall

        Enable a checkpoint firewall data source
        """
        pass

    def test_enable_cisco_aci(self):
        """
        Test case for enable_cisco_aci

        Enable a Cisco ACI data source
        """
        pass

    def test_enable_cisco_asrxr_switch(self):
        """
        Test case for enable_cisco_asrxr_switch

        Enable a Cisco ASRXR switch data source
        """
        pass

    def test_enable_cisco_switch(self):
        """
        Test case for enable_cisco_switch

        Enable a cisco switch data source
        """
        pass

    def test_enable_dell_os10_switch(self):
        """
        Test case for enable_dell_os10_switch

        Enable a dell os10 switch data source
        """
        pass

    def test_enable_dell_switch(self):
        """
        Test case for enable_dell_switch

        Enable a dell switch data source
        """
        pass

    def test_enable_f5_bigip(self):
        """
        Test case for enable_f5_bigip

        Enable a F5 BIG-IP data source
        """
        pass

    def test_enable_fortinet_firewall(self):
        """
        Test case for enable_fortinet_firewall

        Enable a Fortinet firewall data source
        """
        pass

    def test_enable_generic_switch(self):
        """
        Test case for enable_generic_switch

        Enable generic switch data source
        """
        pass

    def test_enable_hcx(self):
        """
        Test case for enable_hcx

        Enable an hcx data source
        """
        pass

    def test_enable_hpe_switch(self):
        """
        Test case for enable_hpe_switch

        Enable a HPE switch data source
        """
        pass

    def test_enable_hpov_manager(self):
        """
        Test case for enable_hpov_manager

        Enable a hp oneview data source
        """
        pass

    def test_enable_hpvc_manager(self):
        """
        Test case for enable_hpvc_manager

        Enable a hpvc manager data source
        """
        pass

    def test_enable_huawei(self):
        """
        Test case for enable_huawei

        Enable a Huawei data source
        """
        pass

    def test_enable_infoblox_manager(self):
        """
        Test case for enable_infoblox_manager

        Enable an infoblox manager data source
        """
        pass

    def test_enable_juniper_switch(self):
        """
        Test case for enable_juniper_switch

        Enable a juniper switch data source
        """
        pass

    def test_enable_kubernetes_cluster(self):
        """
        Test case for enable_kubernetes_cluster

        Enable an kubernetes cluster data source
        """
        pass

    def test_enable_mellanox_switch(self):
        """
        Test case for enable_mellanox_switch

        Enable a Mellanox switch data source
        """
        pass

    def test_enable_nsxalb(self):
        """
        Test case for enable_nsxalb

        Enable an NSX-ALB data source
        """
        pass

    def test_enable_nsxt_manager(self):
        """
        Test case for enable_nsxt_manager

        Enable an nsx-t manager data source
        """
        pass

    def test_enable_nsxv_manager(self):
        """
        Test case for enable_nsxv_manager

        Enable an nsx-v manager data source
        """
        pass

    def test_enable_openshift_cluster(self):
        """
        Test case for enable_openshift_cluster

        Enable an openshift data source
        """
        pass

    def test_enable_panorama_firewall(self):
        """
        Test case for enable_panorama_firewall

        Enable a panorama firewall data source
        """
        pass

    def test_enable_pks(self):
        """
        Test case for enable_pks

        Enable an pks data source
        """
        pass

    def test_enable_policy_manager(self):
        """
        Test case for enable_policy_manager

        Enable a vmc nsx manager data source
        """
        pass

    def test_enable_service_now_instance(self):
        """
        Test case for enable_service_now_instance

        Enable an ServiceNow instance data source
        """
        pass

    def test_enable_ucs_manager(self):
        """
        Test case for enable_ucs_manager

        Enable a ucs manager data source
        """
        pass

    def test_enable_vcenter(self):
        """
        Test case for enable_vcenter

        Enable a vCenter data source
        """
        pass

    def test_enable_velo_cloud(self):
        """
        Test case for enable_velo_cloud

        Enable a velocloud data source
        """
        pass

    def test_file_upload(self):
        """
        Test case for file_upload

        File Upload
        """
        pass

    def test_get_arista_switch(self):
        """
        Test case for get_arista_switch

        Show arista switch data source details
        """
        pass

    def test_get_arista_switch_snmp_config(self):
        """
        Test case for get_arista_switch_snmp_config

        Show snmp config for arista switch data source
        """
        pass

    def test_get_aws_data_source(self):
        """
        Test case for get_aws_data_source

        Show AWS data source details
        """
        pass

    def test_get_azure_subscriptions(self):
        """
        Test case for get_azure_subscriptions

        Show azure data source details
        """
        pass

    def test_get_brocade_switch(self):
        """
        Test case for get_brocade_switch

        Show brocade switch data source details
        """
        pass

    def test_get_brocade_switch_snmp_config(self):
        """
        Test case for get_brocade_switch_snmp_config

        Show snmp config for brocade switch data source
        """
        pass

    def test_get_checkpoint_firewall(self):
        """
        Test case for get_checkpoint_firewall

        Show checkpoint firewall data source details
        """
        pass

    def test_get_cisco_aci(self):
        """
        Test case for get_cisco_aci

        Show Cisco ACI data source details
        """
        pass

    def test_get_cisco_aci_snmp_config(self):
        """
        Test case for get_cisco_aci_snmp_config

        Show snmp config for Cisco ACI
        """
        pass

    def test_get_cisco_asrxr_switch(self):
        """
        Test case for get_cisco_asrxr_switch

        Show Cisco ASRXR switch data source details
        """
        pass

    def test_get_cisco_asrxr_switch_snmp_config(self):
        """
        Test case for get_cisco_asrxr_switch_snmp_config

        Show snmp config for Cisco ASRXR switch data source
        """
        pass

    def test_get_cisco_switch(self):
        """
        Test case for get_cisco_switch

        Show cisco switch data source details
        """
        pass

    def test_get_cisco_switch_snmp_config(self):
        """
        Test case for get_cisco_switch_snmp_config

        Show snmp config for cisco switch data source
        """
        pass

    def test_get_cisco_switch_wan_config(self):
        """
        Test case for get_cisco_switch_wan_config

        Show WAN config for cisco switch data source
        """
        pass

    def test_get_dell_os10_switch(self):
        """
        Test case for get_dell_os10_switch

        Show dell os10 switch data source details
        """
        pass

    def test_get_dell_os10_switch_snmp_config(self):
        """
        Test case for get_dell_os10_switch_snmp_config

        Show snmp config for dell os10 switch data source
        """
        pass

    def test_get_dell_switch(self):
        """
        Test case for get_dell_switch

        Show dell switch data source details
        """
        pass

    def test_get_dell_switch_snmp_config(self):
        """
        Test case for get_dell_switch_snmp_config

        Show snmp config for dell switch data source
        """
        pass

    def test_get_f5_bigip(self):
        """
        Test case for get_f5_bigip

        Show F5 BIG-IP data source details
        """
        pass

    def test_get_f5_bigip_snmp_config(self):
        """
        Test case for get_f5_bigip_snmp_config

        Show snmp config for F5 BIG-IP data source
        """
        pass

    def test_get_fortinet_firewall(self):
        """
        Test case for get_fortinet_firewall

        Show Fortinet firewall data source details
        """
        pass

    def test_get_generic_switch(self):
        """
        Test case for get_generic_switch

        Show generic switch data source details
        """
        pass

    def test_get_hcx(self):
        """
        Test case for get_hcx

        Show hcx data source details
        """
        pass

    def test_get_hpe_switch(self):
        """
        Test case for get_hpe_switch

        Show HPE switch data source details
        """
        pass

    def test_get_hpe_switch_snmp_config(self):
        """
        Test case for get_hpe_switch_snmp_config

        Show snmp config for HPE switch data source
        """
        pass

    def test_get_hpov_manager(self):
        """
        Test case for get_hpov_manager

        Show hp oneview data source details
        """
        pass

    def test_get_hpvc_manager(self):
        """
        Test case for get_hpvc_manager

        Show hpvc data source details
        """
        pass

    def test_get_huawei(self):
        """
        Test case for get_huawei

        Show Huawei data source details
        """
        pass

    def test_get_huawei_snmp_config(self):
        """
        Test case for get_huawei_snmp_config

        Show snmp config for Huawei data source
        """
        pass

    def test_get_infoblox_manager(self):
        """
        Test case for get_infoblox_manager

        Show infoblox manager data source details
        """
        pass

    def test_get_juniper_switch(self):
        """
        Test case for get_juniper_switch

        Show juniper switch data source details
        """
        pass

    def test_get_juniper_switch_snmp_config(self):
        """
        Test case for get_juniper_switch_snmp_config

        Show snmp config for juniper switch data source
        """
        pass

    def test_get_kubernetes_cluster(self):
        """
        Test case for get_kubernetes_cluster

        Show kubernetes cluster data source details
        """
        pass

    def test_get_mellanox_switch(self):
        """
        Test case for get_mellanox_switch

        Show Mellanox switch data source details
        """
        pass

    def test_get_mellanox_switch_snmp_config(self):
        """
        Test case for get_mellanox_switch_snmp_config

        Show snmp config for Mellanox switch data source
        """
        pass

    def test_get_nsxalb(self):
        """
        Test case for get_nsxalb

        Show NSX-ALB data source details
        """
        pass

    def test_get_nsxt_manager(self):
        """
        Test case for get_nsxt_manager

        Show nsx-t manager data source details
        """
        pass

    def test_get_nsxv_controller_cluster(self):
        """
        Test case for get_nsxv_controller_cluster

        Show nsx controller-cluster details
        """
        pass

    def test_get_nsxv_manager(self):
        """
        Test case for get_nsxv_manager

        Show nsx-v manager data source details
        """
        pass

    def test_get_openshift_cluster(self):
        """
        Test case for get_openshift_cluster

        Show Openshift cluster data source details
        """
        pass

    def test_get_panorama_firewall(self):
        """
        Test case for get_panorama_firewall

        Show panorama firewall data source details
        """
        pass

    def test_get_pks(self):
        """
        Test case for get_pks

        Show pks data source details
        """
        pass

    def test_get_policy_manager(self):
        """
        Test case for get_policy_manager

        Show vmc nsx manager data source details
        """
        pass

    def test_get_service_now_instance(self):
        """
        Test case for get_service_now_instance

        Show ServiceNow instance data source details
        """
        pass

    def test_get_ucs_manager(self):
        """
        Test case for get_ucs_manager

        Show ucs manager data source details
        """
        pass

    def test_get_ucs_snmp_config(self):
        """
        Test case for get_ucs_snmp_config

        Show snmp config for ucs fabric interconnects
        """
        pass

    def test_get_vcenter(self):
        """
        Test case for get_vcenter

        Show vCenter data source details
        """
        pass

    def test_get_velo_cloud(self):
        """
        Test case for get_velo_cloud

        Show velocloud data source details
        """
        pass

    def test_list_arista_switches(self):
        """
        Test case for list_arista_switches

        List arista switch data sources
        """
        pass

    def test_list_aws_data_sources(self):
        """
        Test case for list_aws_data_sources

        List AWS data sources
        """
        pass

    def test_list_azure_subscriptions(self):
        """
        Test case for list_azure_subscriptions

        List azure data sources
        """
        pass

    def test_list_brocade_switches(self):
        """
        Test case for list_brocade_switches

        List brocade switch data sources
        """
        pass

    def test_list_checkpoint_firewalls(self):
        """
        Test case for list_checkpoint_firewalls

        List checkpoint firewall data sources
        """
        pass

    def test_list_cisco_aci(self):
        """
        Test case for list_cisco_aci

        List Cisco ACI data sources
        """
        pass

    def test_list_cisco_asrxr_switches(self):
        """
        Test case for list_cisco_asrxr_switches

        List Cisco ASRXR switch data sources
        """
        pass

    def test_list_cisco_switches(self):
        """
        Test case for list_cisco_switches

        List cisco switch data sources
        """
        pass

    def test_list_dell_os10_switches(self):
        """
        Test case for list_dell_os10_switches

        List dell os10 switch data sources
        """
        pass

    def test_list_dell_switches(self):
        """
        Test case for list_dell_switches

        List dell switch data sources
        """
        pass

    def test_list_f5_bigip(self):
        """
        Test case for list_f5_bigip

        List F5 BIG-IP data sources
        """
        pass

    def test_list_fortinet_firewalls(self):
        """
        Test case for list_fortinet_firewalls

        List Fortinet firewall data sources
        """
        pass

    def test_list_generic_switch(self):
        """
        Test case for list_generic_switch

        List generic switch data sources
        """
        pass

    def test_list_hcxs(self):
        """
        Test case for list_hcxs

        List hcx data sources
        """
        pass

    def test_list_hpe_switches(self):
        """
        Test case for list_hpe_switches

        List HPE switch data sources
        """
        pass

    def test_list_hpov_managers(self):
        """
        Test case for list_hpov_managers

        List hp oneview manager data sources
        """
        pass

    def test_list_hpvc_managers(self):
        """
        Test case for list_hpvc_managers

        List hpvc manager data sources
        """
        pass

    def test_list_huawei(self):
        """
        Test case for list_huawei

        List Huawei data sources
        """
        pass

    def test_list_infoblox_managers(self):
        """
        Test case for list_infoblox_managers

        List infoblox manager data sources
        """
        pass

    def test_list_juniper_switches(self):
        """
        Test case for list_juniper_switches

        List juniper switch data sources
        """
        pass

    def test_list_kubernetes_clusters(self):
        """
        Test case for list_kubernetes_clusters

        List kubernetes cluster data sources
        """
        pass

    def test_list_mellanox_switches(self):
        """
        Test case for list_mellanox_switches

        List Mellanox switch data sources
        """
        pass

    def test_list_nsxalb(self):
        """
        Test case for list_nsxalb

        List NSX-ALB data sources
        """
        pass

    def test_list_nsxt_managers(self):
        """
        Test case for list_nsxt_managers

        List nsx-t manager data sources
        """
        pass

    def test_list_nsxv_managers(self):
        """
        Test case for list_nsxv_managers

        List nsx-v manager data sources
        """
        pass

    def test_list_openshift_clusters(self):
        """
        Test case for list_openshift_clusters

        List openshift data sources
        """
        pass

    def test_list_panorama_firewalls(self):
        """
        Test case for list_panorama_firewalls

        List panorama firewall data sources
        """
        pass

    def test_list_pks(self):
        """
        Test case for list_pks

        List pks data sources
        """
        pass

    def test_list_policy_managers(self):
        """
        Test case for list_policy_managers

        List vmc nsx manager data sources
        """
        pass

    def test_list_service_now_instances(self):
        """
        Test case for list_service_now_instances

        List ServiceNow instance data sources
        """
        pass

    def test_list_ucs_managers(self):
        """
        Test case for list_ucs_managers

        List ucs manager data sources
        """
        pass

    def test_list_vcenters(self):
        """
        Test case for list_vcenters

        List vCenter data sources
        """
        pass

    def test_list_velo_cloud(self):
        """
        Test case for list_velo_cloud

        List velocloud data sources
        """
        pass

    def test_update_arista_switch(self):
        """
        Test case for update_arista_switch

        Update an arista switch data source
        """
        pass

    def test_update_arista_switch_snmp_config(self):
        """
        Test case for update_arista_switch_snmp_config

        Update snmp config for arista switch data source
        """
        pass

    def test_update_aws_data_source(self):
        """
        Test case for update_aws_data_source

        Update an AWS data source
        """
        pass

    def test_update_azure_subscription(self):
        """
        Test case for update_azure_subscription

        Update an azure data source
        """
        pass

    def test_update_brocade_switch(self):
        """
        Test case for update_brocade_switch

        Update a brocade switch data source
        """
        pass

    def test_update_brocade_switch_snmp_config(self):
        """
        Test case for update_brocade_switch_snmp_config

        Update snmp config for brocade switch data source
        """
        pass

    def test_update_checkpoint_firewall(self):
        """
        Test case for update_checkpoint_firewall

        Update a checkpoint firewall data source
        """
        pass

    def test_update_cisco_aci_manager(self):
        """
        Test case for update_cisco_aci_manager

        Update a cisco aci data source
        """
        pass

    def test_update_cisco_aci_snmp_config(self):
        """
        Test case for update_cisco_aci_snmp_config

        Update snmp config for Cisco ACI
        """
        pass

    def test_update_cisco_asrxr_switch_manager(self):
        """
        Test case for update_cisco_asrxr_switch_manager

        Update a Cisco ASRXR switch data source
        """
        pass

    def test_update_cisco_asrxr_switch_snmp_config(self):
        """
        Test case for update_cisco_asrxr_switch_snmp_config

        Update snmp config for Cisco ASRXR switch data source
        """
        pass

    def test_update_cisco_switch(self):
        """
        Test case for update_cisco_switch

        Update a cisco switch data source
        """
        pass

    def test_update_cisco_switch_snmp_config(self):
        """
        Test case for update_cisco_switch_snmp_config

        Update snmp config for cisco switch data source
        """
        pass

    def test_update_cisco_switch_wan_config(self):
        """
        Test case for update_cisco_switch_wan_config

        Update WAN config for cisco switch data source
        """
        pass

    def test_update_dell_os10_switch(self):
        """
        Test case for update_dell_os10_switch

        Update a dell os10 switch data source
        """
        pass

    def test_update_dell_os10_switch_snmp_config(self):
        """
        Test case for update_dell_os10_switch_snmp_config

        Update snmp config for dell os10 switch data source
        """
        pass

    def test_update_dell_switch(self):
        """
        Test case for update_dell_switch

        Update a dell switch data source
        """
        pass

    def test_update_dell_switch_snmp_config(self):
        """
        Test case for update_dell_switch_snmp_config

        Update snmp config for dell switch data source
        """
        pass

    def test_update_f5_bigip(self):
        """
        Test case for update_f5_bigip

        Update a F5 BIG-IP data source
        """
        pass

    def test_update_f5_bigip_snmp_config(self):
        """
        Test case for update_f5_bigip_snmp_config

        Update snmp config for a F5 BIG-IP data source
        """
        pass

    def test_update_fortinet_firewall(self):
        """
        Test case for update_fortinet_firewall

        Update a Fortinet firewall data source
        """
        pass

    def test_update_generic_switch(self):
        """
        Test case for update_generic_switch

        Update generic switch data source
        """
        pass

    def test_update_hcx(self):
        """
        Test case for update_hcx

        Update an hcx data source
        """
        pass

    def test_update_hpe_switch_manager(self):
        """
        Test case for update_hpe_switch_manager

        Update a HPE switch data source
        """
        pass

    def test_update_hpe_switch_snmp_config(self):
        """
        Test case for update_hpe_switch_snmp_config

        Update snmp config for HPE switch data source
        """
        pass

    def test_update_hpov_manager(self):
        """
        Test case for update_hpov_manager

        Update a hp oneview data source
        """
        pass

    def test_update_hpvc_manager(self):
        """
        Test case for update_hpvc_manager

        Update a hpvc manager data source
        """
        pass

    def test_update_huawei(self):
        """
        Test case for update_huawei

        Update a Huawei data source
        """
        pass

    def test_update_huawei_snmp_config(self):
        """
        Test case for update_huawei_snmp_config

        Update snmp config for a Huawei data source
        """
        pass

    def test_update_infoblox_manager(self):
        """
        Test case for update_infoblox_manager

        Update an infoblox manager data source
        """
        pass

    def test_update_juniper_switch(self):
        """
        Test case for update_juniper_switch

        Update a juniper switch data source
        """
        pass

    def test_update_juniper_switch_snmp_config(self):
        """
        Test case for update_juniper_switch_snmp_config

        Update snmp config for a juniper switch data source
        """
        pass

    def test_update_kubernetes_cluster(self):
        """
        Test case for update_kubernetes_cluster

        Update an kubernetes cluster data source
        """
        pass

    def test_update_mellanox_switch_manager(self):
        """
        Test case for update_mellanox_switch_manager

        Update a Mellanox switch data source
        """
        pass

    def test_update_mellanox_switch_snmp_config(self):
        """
        Test case for update_mellanox_switch_snmp_config

        Update snmp config for Mellanox switch data source
        """
        pass

    def test_update_nsxalb(self):
        """
        Test case for update_nsxalb

        Update an NSX-ALB data source
        """
        pass

    def test_update_nsxt_manager(self):
        """
        Test case for update_nsxt_manager

        Update an nsx-t manager data source
        """
        pass

    def test_update_nsxv_controller_cluster(self):
        """
        Test case for update_nsxv_controller_cluster

        Update nsx controller-cluster details
        """
        pass

    def test_update_nsxv_manager(self):
        """
        Test case for update_nsxv_manager

        Update an nsx-v manager data source
        """
        pass

    def test_update_openshift_cluster(self):
        """
        Test case for update_openshift_cluster

        Update an openshift data source
        """
        pass

    def test_update_panorama_firewall(self):
        """
        Test case for update_panorama_firewall

        Update a panorama firewall data source
        """
        pass

    def test_update_pks(self):
        """
        Test case for update_pks

        Update an pks data source
        """
        pass

    def test_update_policy_manager(self):
        """
        Test case for update_policy_manager

        Update a vmc nsx manager data source
        """
        pass

    def test_update_service_now_instance(self):
        """
        Test case for update_service_now_instance

        Update an ServiceNow instance data source
        """
        pass

    def test_update_ucs_manager(self):
        """
        Test case for update_ucs_manager

        Update a ucs manager data source
        """
        pass

    def test_update_ucs_snmp_config(self):
        """
        Test case for update_ucs_snmp_config

        Update snmp config for ucs fabric interconnects
        """
        pass

    def test_update_vcenter(self):
        """
        Test case for update_vcenter

        Update a vCenter data source.
        """
        pass

    def test_update_velo_cloud(self):
        """
        Test case for update_velo_cloud

        Update a velocloud data source
        """
        pass


if __name__ == '__main__':
    unittest.main()
