import swagger_client.models.data_source_type as data_source_type


def get_api_function_name(datasource_type):
    datasource = {
        data_source_type.DataSourceType.CISCOSWITCHDATASOURCE: {"update_snmp_config": "update_cisco_switch_snmp_config",
                                                                "get_snmp_config": "get_cisco_switch_snmp_config",
                                                                "update": "update_cisco_switch",
                                                                "get": "get_cisco_switch",
                                                                "list": "list_cisco_switches",
                                                                "delete": "delete_cisco_switch",
                                                                "enable":"enable_cisco_switch",
                                                                "disable":"disable_cisco_switch"},
        data_source_type.DataSourceType.DELLSWITCHDATASOURCE: {"update_snmp_config": "update_dell_switch_snmp_config",
                                                               "get_snmp_config": "get_dell_switch_snmp_config",
                                                               "update": "update_dell_switch",
                                                               "get": "get_dell_switch",
                                                               "list": "list_dell_switches",
                                                               "delete": "delete_dell_switch",
                                                               "enable":"enable_dell_switch",
                                                               "disable":"disable_dell_switch"},
        data_source_type.DataSourceType.ARISTASWITCHDATASOURCE: {"update_snmp_config": "update_arista_switch_snmp_config",
                                                                 "get_snmp_config": "get_arista_switch_snmp_config",
                                                                 "update": "update_arista_switch",
                                                                 "get": "get_arista_switch",
                                                                 "list": "list_arista_switches",
                                                                 "delete": "delete_arista_switch",
                                                                 "enable":"enable_arista_switch",
                                                                 "disable":"disable_arista_switch"},
        data_source_type.DataSourceType.BROCADESWITCHDATASOURCE: {"update_snmp_config": "update_brocade_switch_snmp_config",
                                                                  "get_snmp_config": "get_brocade_switch_snmp_config",
                                                                  "update": "update_brocade_switch",
                                                                  "get": "get_brocade_switch",
                                                                  "list": "list_brocade_switches",
                                                                  "delete": "delete_brocade_switch"},
        data_source_type.DataSourceType.JUNIPERSWITCHDATASOURCE: {"update_snmp_config": "update_juniper_switch_snmp_config",
                                                                  "get_snmp_config": "get_juniper_switch_snmp_config",
                                                                  "update": "update_juniper_switch",
                                                                  "get": "get_juniper_switch",
                                                                  "list": "list_juniper_switches",
                                                                  "delete": "delete_juniper_switch"},
        data_source_type.DataSourceType.VCENTERDATASOURCE: {"update": "update_vcenter",
                                                            "get": "get_vcenter",
                                                            "list": "list_vcenters",
                                                            "delete": "delete_vcenter",
                                                            "enable":"enable_vcenter",
                                                            "disable":"disable_vcenter"},
        data_source_type.DataSourceType.NSXVMANAGERDATASOURCE: {"update": "update_nsxv_manager",
                                                                "get": "get_nsxv_manager",
                                                                "list": "list_nsxv_managers",
                                                                "delete": "delete_nsxv_manager",
                                                                "enable":"enable_nsxv_manager",
                                                                "disable":"disable_nsxv_manager"},
        data_source_type.DataSourceType.UCSMANAGERDATASOURCE: {"update_snmp_config": "update_ucs_snmp_config",
                                                               "get_snmp_config": "get_ucs_snmp_config",
                                                               "update": "update_ucs_manager",
                                                               "get": "get_ucs_manager",
                                                               "list": "list_ucs_managers",
                                                               "delete":"delete_ucs_manager"},
        data_source_type.DataSourceType.HPVCMANAGERDATASOURCE: {"update": "update_hpvc_manager",
                                                                "get": "get_hpvc_manager",
                                                                "list": "list_hpvc_managers",
                                                                "delete":"delete_hpvc_manager"},
        data_source_type.DataSourceType.HPONEVIEWDATASOURCE: {"update": "update_hpov_manager",
                                                              "get": "get_hpov_manager",
                                                              "list": "list_hpov_managers",
                                                              "delete":"delete_hpov_manager"},
        data_source_type.DataSourceType.PANFIREWALLDATASOURCE: {"update": "update_panorama_firewall",
                                                                "get": "get_panorama_firewall",
                                                                "list": "list_panorama_firewalls",
                                                                "delete":"delete_panorama_firewall",
                                                                "enable":"enable_panorama_firewall",
                                                                "disable":"disable_panorama_firewall"},
        data_source_type.DataSourceType.CHECKPOINTFIREWALLDATASOURCE: {"update": "update_checkpoint_firewall",
                                                                       "get": "get_checkpoint_firewall",
                                                                       "list": "list_checkpoint_firewalls",
                                                                       "delete":"delete_checkpoint_firewall"},
        data_source_type.DataSourceType.NSXTMANAGERDATASOURCE: {"update": "update_nsxt_manager",
                                                                "get": "get_nsxt_manager",
                                                                "list": "list_nsxt_managers",
                                                                "delete":"delete_nsxt_manager",
                                                                "enable":"enable_nsxt_manager",
                                                                "disable":"disable_nsxt_manager"},
        data_source_type.DataSourceType.KUBERNETESDATASOURCE: {"update": "update_kubernetes_datasource",
                                                               "get": "get_kubernetes_cluster",
                                                               "list": "list_kubernetes_clusters",
                                                               "delete":"delete_kubernetes_cluster"},
        data_source_type.DataSourceType.F5BIGIPDATASOURCE: {"update_snmp_config": "update_f5_bigip_snmp_config",
                                                            "get_snmp_config": "get_f5_bigip_snmp_config",
                                                            "update": "update_f5_bigip",
                                                            "get": "get_f5_bigip",
                                                            "list": "list_f5_bigip",
                                                            "delete":"delete_f5_bigip"},
        data_source_type.DataSourceType.POLICYMANAGERDATASOURCE: {"update": "update_policy_manager",
                                                                  "get": "get_policy_manager",
                                                                  "list": "list_policy_managers",
                                                                  "delete":"delete_policy_manager"}}

    return datasource[datasource_type]
