# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApplicationFlowSummary(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_endpoint_count': 'int',
        'groups': 'list[GroupEntry]',
        'start_time': 'int',
        'end_time': 'int'
    }

    attribute_map = {
        'service_endpoint_count': 'service_endpoint_count',
        'groups': 'groups',
        'start_time': 'start_time',
        'end_time': 'end_time'
    }

    def __init__(self, service_endpoint_count=None, groups=None, start_time=None, end_time=None):
        """
        ApplicationFlowSummary - a model defined in Swagger
        """

        self._service_endpoint_count = None
        self._groups = None
        self._start_time = None
        self._end_time = None

        if service_endpoint_count is not None:
          self.service_endpoint_count = service_endpoint_count
        if groups is not None:
          self.groups = groups
        if start_time is not None:
          self.start_time = start_time
        if end_time is not None:
          self.end_time = end_time

    @property
    def service_endpoint_count(self):
        """
        Gets the service_endpoint_count of this ApplicationFlowSummary.

        :return: The service_endpoint_count of this ApplicationFlowSummary.
        :rtype: int
        """
        return self._service_endpoint_count

    @service_endpoint_count.setter
    def service_endpoint_count(self, service_endpoint_count):
        """
        Sets the service_endpoint_count of this ApplicationFlowSummary.

        :param service_endpoint_count: The service_endpoint_count of this ApplicationFlowSummary.
        :type: int
        """

        self._service_endpoint_count = service_endpoint_count

    @property
    def groups(self):
        """
        Gets the groups of this ApplicationFlowSummary.

        :return: The groups of this ApplicationFlowSummary.
        :rtype: list[GroupEntry]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """
        Sets the groups of this ApplicationFlowSummary.

        :param groups: The groups of this ApplicationFlowSummary.
        :type: list[GroupEntry]
        """

        self._groups = groups

    @property
    def start_time(self):
        """
        Gets the start_time of this ApplicationFlowSummary.

        :return: The start_time of this ApplicationFlowSummary.
        :rtype: int
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """
        Sets the start_time of this ApplicationFlowSummary.

        :param start_time: The start_time of this ApplicationFlowSummary.
        :type: int
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """
        Gets the end_time of this ApplicationFlowSummary.

        :return: The end_time of this ApplicationFlowSummary.
        :rtype: int
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """
        Sets the end_time of this ApplicationFlowSummary.

        :param end_time: The end_time of this ApplicationFlowSummary.
        :type: int
        """

        self._end_time = end_time

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApplicationFlowSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
