# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApplicationFlowData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application_id': 'str',
        'flow_data': 'list[FlowData]'
    }

    attribute_map = {
        'application_id': 'application_id',
        'flow_data': 'flow_data'
    }

    def __init__(self, application_id=None, flow_data=None):
        """
        ApplicationFlowData - a model defined in Swagger
        """

        self._application_id = None
        self._flow_data = None

        if application_id is not None:
          self.application_id = application_id
        if flow_data is not None:
          self.flow_data = flow_data

    @property
    def application_id(self):
        """
        Gets the application_id of this ApplicationFlowData.

        :return: The application_id of this ApplicationFlowData.
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """
        Sets the application_id of this ApplicationFlowData.

        :param application_id: The application_id of this ApplicationFlowData.
        :type: str
        """

        self._application_id = application_id

    @property
    def flow_data(self):
        """
        Gets the flow_data of this ApplicationFlowData.

        :return: The flow_data of this ApplicationFlowData.
        :rtype: list[FlowData]
        """
        return self._flow_data

    @flow_data.setter
    def flow_data(self, flow_data):
        """
        Sets the flow_data of this ApplicationFlowData.

        :param flow_data: The flow_data of this ApplicationFlowData.
        :type: list[FlowData]
        """

        self._flow_data = flow_data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApplicationFlowData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
