# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CustomerUsageDataResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'deployment_id': 'str',
        'customer_id': 'int',
        'org_id': 'str',
        'status': 'str',
        'usage': 'CustomerUsageData'
    }

    attribute_map = {
        'deployment_id': 'deploymentId',
        'customer_id': 'customerId',
        'org_id': 'orgId',
        'status': 'status',
        'usage': 'usage'
    }

    def __init__(self, deployment_id=None, customer_id=None, org_id=None, status=None, usage=None):
        """
        CustomerUsageDataResponse - a model defined in Swagger
        """

        self._deployment_id = None
        self._customer_id = None
        self._org_id = None
        self._status = None
        self._usage = None

        if deployment_id is not None:
          self.deployment_id = deployment_id
        if customer_id is not None:
          self.customer_id = customer_id
        if org_id is not None:
          self.org_id = org_id
        if status is not None:
          self.status = status
        if usage is not None:
          self.usage = usage

    @property
    def deployment_id(self):
        """
        Gets the deployment_id of this CustomerUsageDataResponse.
        Deployment ID

        :return: The deployment_id of this CustomerUsageDataResponse.
        :rtype: str
        """
        return self._deployment_id

    @deployment_id.setter
    def deployment_id(self, deployment_id):
        """
        Sets the deployment_id of this CustomerUsageDataResponse.
        Deployment ID

        :param deployment_id: The deployment_id of this CustomerUsageDataResponse.
        :type: str
        """

        self._deployment_id = deployment_id

    @property
    def customer_id(self):
        """
        Gets the customer_id of this CustomerUsageDataResponse.
        customerId

        :return: The customer_id of this CustomerUsageDataResponse.
        :rtype: int
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """
        Sets the customer_id of this CustomerUsageDataResponse.
        customerId

        :param customer_id: The customer_id of this CustomerUsageDataResponse.
        :type: int
        """

        self._customer_id = customer_id

    @property
    def org_id(self):
        """
        Gets the org_id of this CustomerUsageDataResponse.
        Organization ID (Only in case of VRNI-Cloud)

        :return: The org_id of this CustomerUsageDataResponse.
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """
        Sets the org_id of this CustomerUsageDataResponse.
        Organization ID (Only in case of VRNI-Cloud)

        :param org_id: The org_id of this CustomerUsageDataResponse.
        :type: str
        """

        self._org_id = org_id

    @property
    def status(self):
        """
        Gets the status of this CustomerUsageDataResponse.

        :return: The status of this CustomerUsageDataResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this CustomerUsageDataResponse.

        :param status: The status of this CustomerUsageDataResponse.
        :type: str
        """
        allowed_values = ["SUCCESS", "FAILED"]
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def usage(self):
        """
        Gets the usage of this CustomerUsageDataResponse.

        :return: The usage of this CustomerUsageDataResponse.
        :rtype: CustomerUsageData
        """
        return self._usage

    @usage.setter
    def usage(self, usage):
        """
        Sets the usage of this CustomerUsageDataResponse.

        :param usage: The usage of this CustomerUsageDataResponse.
        :type: CustomerUsageData
        """

        self._usage = usage

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CustomerUsageDataResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
