# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ServiceNowDataSource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_id': 'str',
        'entity_type': 'DataSourceType',
        'ip': 'str',
        'fqdn': 'str',
        'proxy_id': 'str',
        'nickname': 'str',
        'enabled': 'bool',
        'notes': 'str',
        'credentials': 'PasswordCredentials',
        'instance_id': 'str',
        'graph_configuration': 'str',
        'is_graph_config_customized': 'bool'
    }

    attribute_map = {
        'entity_id': 'entity_id',
        'entity_type': 'entity_type',
        'ip': 'ip',
        'fqdn': 'fqdn',
        'proxy_id': 'proxy_id',
        'nickname': 'nickname',
        'enabled': 'enabled',
        'notes': 'notes',
        'credentials': 'credentials',
        'instance_id': 'instance_id',
        'graph_configuration': 'graph_configuration',
        'is_graph_config_customized': 'is_graph_config_customized'
    }

    def __init__(self, entity_id=None, entity_type=None, ip=None, fqdn=None, proxy_id=None, nickname=None, enabled=True, notes=None, credentials=None, instance_id=None, graph_configuration=None, is_graph_config_customized=None):
        """
        ServiceNowDataSource - a model defined in Swagger
        """

        self._entity_id = None
        self._entity_type = None
        self._ip = None
        self._fqdn = None
        self._proxy_id = None
        self._nickname = None
        self._enabled = None
        self._notes = None
        self._credentials = None
        self._instance_id = None
        self._graph_configuration = None
        self._is_graph_config_customized = None

        if entity_id is not None:
          self.entity_id = entity_id
        if entity_type is not None:
          self.entity_type = entity_type
        if ip is not None:
          self.ip = ip
        if fqdn is not None:
          self.fqdn = fqdn
        if proxy_id is not None:
          self.proxy_id = proxy_id
        if nickname is not None:
          self.nickname = nickname
        if enabled is not None:
          self.enabled = enabled
        if notes is not None:
          self.notes = notes
        if credentials is not None:
          self.credentials = credentials
        if instance_id is not None:
          self.instance_id = instance_id
        if graph_configuration is not None:
          self.graph_configuration = graph_configuration
        if is_graph_config_customized is not None:
          self.is_graph_config_customized = is_graph_config_customized

    @property
    def entity_id(self):
        """
        Gets the entity_id of this ServiceNowDataSource.

        :return: The entity_id of this ServiceNowDataSource.
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """
        Sets the entity_id of this ServiceNowDataSource.

        :param entity_id: The entity_id of this ServiceNowDataSource.
        :type: str
        """

        self._entity_id = entity_id

    @property
    def entity_type(self):
        """
        Gets the entity_type of this ServiceNowDataSource.

        :return: The entity_type of this ServiceNowDataSource.
        :rtype: DataSourceType
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """
        Sets the entity_type of this ServiceNowDataSource.

        :param entity_type: The entity_type of this ServiceNowDataSource.
        :type: DataSourceType
        """

        self._entity_type = entity_type

    @property
    def ip(self):
        """
        Gets the ip of this ServiceNowDataSource.

        :return: The ip of this ServiceNowDataSource.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """
        Sets the ip of this ServiceNowDataSource.

        :param ip: The ip of this ServiceNowDataSource.
        :type: str
        """

        self._ip = ip

    @property
    def fqdn(self):
        """
        Gets the fqdn of this ServiceNowDataSource.

        :return: The fqdn of this ServiceNowDataSource.
        :rtype: str
        """
        return self._fqdn

    @fqdn.setter
    def fqdn(self, fqdn):
        """
        Sets the fqdn of this ServiceNowDataSource.

        :param fqdn: The fqdn of this ServiceNowDataSource.
        :type: str
        """

        self._fqdn = fqdn

    @property
    def proxy_id(self):
        """
        Gets the proxy_id of this ServiceNowDataSource.
        proxy vm which should register this vcenter

        :return: The proxy_id of this ServiceNowDataSource.
        :rtype: str
        """
        return self._proxy_id

    @proxy_id.setter
    def proxy_id(self, proxy_id):
        """
        Sets the proxy_id of this ServiceNowDataSource.
        proxy vm which should register this vcenter

        :param proxy_id: The proxy_id of this ServiceNowDataSource.
        :type: str
        """

        self._proxy_id = proxy_id

    @property
    def nickname(self):
        """
        Gets the nickname of this ServiceNowDataSource.

        :return: The nickname of this ServiceNowDataSource.
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """
        Sets the nickname of this ServiceNowDataSource.

        :param nickname: The nickname of this ServiceNowDataSource.
        :type: str
        """

        self._nickname = nickname

    @property
    def enabled(self):
        """
        Gets the enabled of this ServiceNowDataSource.

        :return: The enabled of this ServiceNowDataSource.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """
        Sets the enabled of this ServiceNowDataSource.

        :param enabled: The enabled of this ServiceNowDataSource.
        :type: bool
        """

        self._enabled = enabled

    @property
    def notes(self):
        """
        Gets the notes of this ServiceNowDataSource.

        :return: The notes of this ServiceNowDataSource.
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """
        Sets the notes of this ServiceNowDataSource.

        :param notes: The notes of this ServiceNowDataSource.
        :type: str
        """

        self._notes = notes

    @property
    def credentials(self):
        """
        Gets the credentials of this ServiceNowDataSource.

        :return: The credentials of this ServiceNowDataSource.
        :rtype: PasswordCredentials
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """
        Sets the credentials of this ServiceNowDataSource.

        :param credentials: The credentials of this ServiceNowDataSource.
        :type: PasswordCredentials
        """

        self._credentials = credentials

    @property
    def instance_id(self):
        """
        Gets the instance_id of this ServiceNowDataSource.
        Associated nsxt data source entity Id

        :return: The instance_id of this ServiceNowDataSource.
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id):
        """
        Sets the instance_id of this ServiceNowDataSource.
        Associated nsxt data source entity Id

        :param instance_id: The instance_id of this ServiceNowDataSource.
        :type: str
        """

        self._instance_id = instance_id

    @property
    def graph_configuration(self):
        """
        Gets the graph_configuration of this ServiceNowDataSource.
        CMDB configuration for CIs, relationships and graph traversal rules

        :return: The graph_configuration of this ServiceNowDataSource.
        :rtype: str
        """
        return self._graph_configuration

    @graph_configuration.setter
    def graph_configuration(self, graph_configuration):
        """
        Sets the graph_configuration of this ServiceNowDataSource.
        CMDB configuration for CIs, relationships and graph traversal rules

        :param graph_configuration: The graph_configuration of this ServiceNowDataSource.
        :type: str
        """

        self._graph_configuration = graph_configuration

    @property
    def is_graph_config_customized(self):
        """
        Gets the is_graph_config_customized of this ServiceNowDataSource.
        Has graph configuration been modified from the default configuration

        :return: The is_graph_config_customized of this ServiceNowDataSource.
        :rtype: bool
        """
        return self._is_graph_config_customized

    @is_graph_config_customized.setter
    def is_graph_config_customized(self, is_graph_config_customized):
        """
        Sets the is_graph_config_customized of this ServiceNowDataSource.
        Has graph configuration been modified from the default configuration

        :param is_graph_config_customized: The is_graph_config_customized of this ServiceNowDataSource.
        :type: bool
        """

        self._is_graph_config_customized = is_graph_config_customized

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list([x.to_dict() if hasattr(x, "to_dict") else x for x in value])
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict([(item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item for item in list(value.items())])
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ServiceNowDataSource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
