# coding: utf-8

"""
    vRealize Network Insight API Reference

    vRealize Network Insight API Reference

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class VMCCapacityThresholdBreachEvent(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_id': 'str',
        'name': 'str',
        'entity_type': 'EntityType',
        'anchor_entities': 'list[Reference]',
        'related_entities': 'list[Reference]',
        'message': 'str',
        'event_tags': 'list[str]',
        'admin_state': 'str',
        'archived': 'bool',
        'event_time_epoch_ms': 'int',
        'event_type': 'str',
        'recommendations': 'list[str]',
        'severity': 'str',
        'event_close_time_epoch_ms': 'int',
        'absolute_limit': 'int',
        'upper_threshold': 'int',
        'lower_threshold': 'int',
        'is_percentage': 'bool',
        'sub_type': 'str',
        'alert_entity_type': 'EntityType',
        'entity_count': 'int',
        'sddc_id': 'str',
        'org_id': 'str'
    }

    attribute_map = {
        'entity_id': 'entity_id',
        'name': 'name',
        'entity_type': 'entity_type',
        'anchor_entities': 'anchor_entities',
        'related_entities': 'related_entities',
        'message': 'message',
        'event_tags': 'event_tags',
        'admin_state': 'admin_state',
        'archived': 'archived',
        'event_time_epoch_ms': 'event_time_epoch_ms',
        'event_type': 'event_type',
        'recommendations': 'recommendations',
        'severity': 'severity',
        'event_close_time_epoch_ms': 'event_close_time_epoch_ms',
        'absolute_limit': 'absolute_limit',
        'upper_threshold': 'upper_threshold',
        'lower_threshold': 'lower_threshold',
        'is_percentage': 'is_percentage',
        'sub_type': 'sub_type',
        'alert_entity_type': 'alert_entity_type',
        'entity_count': 'entity_count',
        'sddc_id': 'sddc_id',
        'org_id': 'org_id'
    }

    def __init__(self, entity_id=None, name=None, entity_type=None, anchor_entities=None, related_entities=None, message=None, event_tags=None, admin_state=None, archived=None, event_time_epoch_ms=None, event_type=None, recommendations=None, severity=None, event_close_time_epoch_ms=None, absolute_limit=None, upper_threshold=None, lower_threshold=None, is_percentage=None, sub_type=None, alert_entity_type=None, entity_count=None, sddc_id=None, org_id=None):
        """
        VMCCapacityThresholdBreachEvent - a model defined in Swagger
        """

        self._entity_id = None
        self._name = None
        self._entity_type = None
        self._anchor_entities = None
        self._related_entities = None
        self._message = None
        self._event_tags = None
        self._admin_state = None
        self._archived = None
        self._event_time_epoch_ms = None
        self._event_type = None
        self._recommendations = None
        self._severity = None
        self._event_close_time_epoch_ms = None
        self._absolute_limit = None
        self._upper_threshold = None
        self._lower_threshold = None
        self._is_percentage = None
        self._sub_type = None
        self._alert_entity_type = None
        self._entity_count = None
        self._sddc_id = None
        self._org_id = None

        if entity_id is not None:
          self.entity_id = entity_id
        if name is not None:
          self.name = name
        if entity_type is not None:
          self.entity_type = entity_type
        if anchor_entities is not None:
          self.anchor_entities = anchor_entities
        if related_entities is not None:
          self.related_entities = related_entities
        if message is not None:
          self.message = message
        if event_tags is not None:
          self.event_tags = event_tags
        if admin_state is not None:
          self.admin_state = admin_state
        if archived is not None:
          self.archived = archived
        if event_time_epoch_ms is not None:
          self.event_time_epoch_ms = event_time_epoch_ms
        if event_type is not None:
          self.event_type = event_type
        if recommendations is not None:
          self.recommendations = recommendations
        if severity is not None:
          self.severity = severity
        if event_close_time_epoch_ms is not None:
          self.event_close_time_epoch_ms = event_close_time_epoch_ms
        if absolute_limit is not None:
          self.absolute_limit = absolute_limit
        if upper_threshold is not None:
          self.upper_threshold = upper_threshold
        if lower_threshold is not None:
          self.lower_threshold = lower_threshold
        if is_percentage is not None:
          self.is_percentage = is_percentage
        if sub_type is not None:
          self.sub_type = sub_type
        if alert_entity_type is not None:
          self.alert_entity_type = alert_entity_type
        if entity_count is not None:
          self.entity_count = entity_count
        if sddc_id is not None:
          self.sddc_id = sddc_id
        if org_id is not None:
          self.org_id = org_id

    @property
    def entity_id(self):
        """
        Gets the entity_id of this VMCCapacityThresholdBreachEvent.
        Entity ID that can be references in detail API calls

        :return: The entity_id of this VMCCapacityThresholdBreachEvent.
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """
        Sets the entity_id of this VMCCapacityThresholdBreachEvent.
        Entity ID that can be references in detail API calls

        :param entity_id: The entity_id of this VMCCapacityThresholdBreachEvent.
        :type: str
        """

        self._entity_id = entity_id

    @property
    def name(self):
        """
        Gets the name of this VMCCapacityThresholdBreachEvent.
        Name of the object

        :return: The name of this VMCCapacityThresholdBreachEvent.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this VMCCapacityThresholdBreachEvent.
        Name of the object

        :param name: The name of this VMCCapacityThresholdBreachEvent.
        :type: str
        """

        self._name = name

    @property
    def entity_type(self):
        """
        Gets the entity_type of this VMCCapacityThresholdBreachEvent.

        :return: The entity_type of this VMCCapacityThresholdBreachEvent.
        :rtype: EntityType
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """
        Sets the entity_type of this VMCCapacityThresholdBreachEvent.

        :param entity_type: The entity_type of this VMCCapacityThresholdBreachEvent.
        :type: EntityType
        """

        self._entity_type = entity_type

    @property
    def anchor_entities(self):
        """
        Gets the anchor_entities of this VMCCapacityThresholdBreachEvent.

        :return: The anchor_entities of this VMCCapacityThresholdBreachEvent.
        :rtype: list[Reference]
        """
        return self._anchor_entities

    @anchor_entities.setter
    def anchor_entities(self, anchor_entities):
        """
        Sets the anchor_entities of this VMCCapacityThresholdBreachEvent.

        :param anchor_entities: The anchor_entities of this VMCCapacityThresholdBreachEvent.
        :type: list[Reference]
        """

        self._anchor_entities = anchor_entities

    @property
    def related_entities(self):
        """
        Gets the related_entities of this VMCCapacityThresholdBreachEvent.
        The entity IDs of all related objects

        :return: The related_entities of this VMCCapacityThresholdBreachEvent.
        :rtype: list[Reference]
        """
        return self._related_entities

    @related_entities.setter
    def related_entities(self, related_entities):
        """
        Sets the related_entities of this VMCCapacityThresholdBreachEvent.
        The entity IDs of all related objects

        :param related_entities: The related_entities of this VMCCapacityThresholdBreachEvent.
        :type: list[Reference]
        """

        self._related_entities = related_entities

    @property
    def message(self):
        """
        Gets the message of this VMCCapacityThresholdBreachEvent.
        Event message

        :return: The message of this VMCCapacityThresholdBreachEvent.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this VMCCapacityThresholdBreachEvent.
        Event message

        :param message: The message of this VMCCapacityThresholdBreachEvent.
        :type: str
        """

        self._message = message

    @property
    def event_tags(self):
        """
        Gets the event_tags of this VMCCapacityThresholdBreachEvent.
        Event tags

        :return: The event_tags of this VMCCapacityThresholdBreachEvent.
        :rtype: list[str]
        """
        return self._event_tags

    @event_tags.setter
    def event_tags(self, event_tags):
        """
        Sets the event_tags of this VMCCapacityThresholdBreachEvent.
        Event tags

        :param event_tags: The event_tags of this VMCCapacityThresholdBreachEvent.
        :type: list[str]
        """

        self._event_tags = event_tags

    @property
    def admin_state(self):
        """
        Gets the admin_state of this VMCCapacityThresholdBreachEvent.
        Administrative state of the event

        :return: The admin_state of this VMCCapacityThresholdBreachEvent.
        :rtype: str
        """
        return self._admin_state

    @admin_state.setter
    def admin_state(self, admin_state):
        """
        Sets the admin_state of this VMCCapacityThresholdBreachEvent.
        Administrative state of the event

        :param admin_state: The admin_state of this VMCCapacityThresholdBreachEvent.
        :type: str
        """
        allowed_values = ["ENABLED", "DISABLED"]
        if admin_state not in allowed_values:
            raise ValueError(
                "Invalid value for `admin_state` ({0}), must be one of {1}"
                .format(admin_state, allowed_values)
            )

        self._admin_state = admin_state

    @property
    def archived(self):
        """
        Gets the archived of this VMCCapacityThresholdBreachEvent.
        Whether of not the event is archived

        :return: The archived of this VMCCapacityThresholdBreachEvent.
        :rtype: bool
        """
        return self._archived

    @archived.setter
    def archived(self, archived):
        """
        Sets the archived of this VMCCapacityThresholdBreachEvent.
        Whether of not the event is archived

        :param archived: The archived of this VMCCapacityThresholdBreachEvent.
        :type: bool
        """

        self._archived = archived

    @property
    def event_time_epoch_ms(self):
        """
        Gets the event_time_epoch_ms of this VMCCapacityThresholdBreachEvent.
        Epoc timestamp of when the event was triggered

        :return: The event_time_epoch_ms of this VMCCapacityThresholdBreachEvent.
        :rtype: int
        """
        return self._event_time_epoch_ms

    @event_time_epoch_ms.setter
    def event_time_epoch_ms(self, event_time_epoch_ms):
        """
        Sets the event_time_epoch_ms of this VMCCapacityThresholdBreachEvent.
        Epoc timestamp of when the event was triggered

        :param event_time_epoch_ms: The event_time_epoch_ms of this VMCCapacityThresholdBreachEvent.
        :type: int
        """

        self._event_time_epoch_ms = event_time_epoch_ms

    @property
    def event_type(self):
        """
        Gets the event_type of this VMCCapacityThresholdBreachEvent.
        The type of event

        :return: The event_type of this VMCCapacityThresholdBreachEvent.
        :rtype: str
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type):
        """
        Sets the event_type of this VMCCapacityThresholdBreachEvent.
        The type of event

        :param event_type: The event_type of this VMCCapacityThresholdBreachEvent.
        :type: str
        """

        self._event_type = event_type

    @property
    def recommendations(self):
        """
        Gets the recommendations of this VMCCapacityThresholdBreachEvent.
        A list of recommended remedies

        :return: The recommendations of this VMCCapacityThresholdBreachEvent.
        :rtype: list[str]
        """
        return self._recommendations

    @recommendations.setter
    def recommendations(self, recommendations):
        """
        Sets the recommendations of this VMCCapacityThresholdBreachEvent.
        A list of recommended remedies

        :param recommendations: The recommendations of this VMCCapacityThresholdBreachEvent.
        :type: list[str]
        """

        self._recommendations = recommendations

    @property
    def severity(self):
        """
        Gets the severity of this VMCCapacityThresholdBreachEvent.

        :return: The severity of this VMCCapacityThresholdBreachEvent.
        :rtype: str
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """
        Sets the severity of this VMCCapacityThresholdBreachEvent.

        :param severity: The severity of this VMCCapacityThresholdBreachEvent.
        :type: str
        """
        allowed_values = ["CRITICAL", "MODERATE", "WARNING", "INFO"]
        if severity not in allowed_values:
            raise ValueError(
                "Invalid value for `severity` ({0}), must be one of {1}"
                .format(severity, allowed_values)
            )

        self._severity = severity

    @property
    def event_close_time_epoch_ms(self):
        """
        Gets the event_close_time_epoch_ms of this VMCCapacityThresholdBreachEvent.

        :return: The event_close_time_epoch_ms of this VMCCapacityThresholdBreachEvent.
        :rtype: int
        """
        return self._event_close_time_epoch_ms

    @event_close_time_epoch_ms.setter
    def event_close_time_epoch_ms(self, event_close_time_epoch_ms):
        """
        Sets the event_close_time_epoch_ms of this VMCCapacityThresholdBreachEvent.

        :param event_close_time_epoch_ms: The event_close_time_epoch_ms of this VMCCapacityThresholdBreachEvent.
        :type: int
        """

        self._event_close_time_epoch_ms = event_close_time_epoch_ms

    @property
    def absolute_limit(self):
        """
        Gets the absolute_limit of this VMCCapacityThresholdBreachEvent.
        The configured absolute limit.

        :return: The absolute_limit of this VMCCapacityThresholdBreachEvent.
        :rtype: int
        """
        return self._absolute_limit

    @absolute_limit.setter
    def absolute_limit(self, absolute_limit):
        """
        Sets the absolute_limit of this VMCCapacityThresholdBreachEvent.
        The configured absolute limit.

        :param absolute_limit: The absolute_limit of this VMCCapacityThresholdBreachEvent.
        :type: int
        """

        self._absolute_limit = absolute_limit

    @property
    def upper_threshold(self):
        """
        Gets the upper_threshold of this VMCCapacityThresholdBreachEvent.
        The configured upper threshold value at which the alert is raised.

        :return: The upper_threshold of this VMCCapacityThresholdBreachEvent.
        :rtype: int
        """
        return self._upper_threshold

    @upper_threshold.setter
    def upper_threshold(self, upper_threshold):
        """
        Sets the upper_threshold of this VMCCapacityThresholdBreachEvent.
        The configured upper threshold value at which the alert is raised.

        :param upper_threshold: The upper_threshold of this VMCCapacityThresholdBreachEvent.
        :type: int
        """

        self._upper_threshold = upper_threshold

    @property
    def lower_threshold(self):
        """
        Gets the lower_threshold of this VMCCapacityThresholdBreachEvent.
        The configured lower threshold value at which the alert is raised.

        :return: The lower_threshold of this VMCCapacityThresholdBreachEvent.
        :rtype: int
        """
        return self._lower_threshold

    @lower_threshold.setter
    def lower_threshold(self, lower_threshold):
        """
        Sets the lower_threshold of this VMCCapacityThresholdBreachEvent.
        The configured lower threshold value at which the alert is raised.

        :param lower_threshold: The lower_threshold of this VMCCapacityThresholdBreachEvent.
        :type: int
        """

        self._lower_threshold = lower_threshold

    @property
    def is_percentage(self):
        """
        Gets the is_percentage of this VMCCapacityThresholdBreachEvent.
        Indicates whether the threshold value is in percentage of the absolute limt or not.

        :return: The is_percentage of this VMCCapacityThresholdBreachEvent.
        :rtype: bool
        """
        return self._is_percentage

    @is_percentage.setter
    def is_percentage(self, is_percentage):
        """
        Sets the is_percentage of this VMCCapacityThresholdBreachEvent.
        Indicates whether the threshold value is in percentage of the absolute limt or not.

        :param is_percentage: The is_percentage of this VMCCapacityThresholdBreachEvent.
        :type: bool
        """

        self._is_percentage = is_percentage

    @property
    def sub_type(self):
        """
        Gets the sub_type of this VMCCapacityThresholdBreachEvent.
        Event sub-type.

        :return: The sub_type of this VMCCapacityThresholdBreachEvent.
        :rtype: str
        """
        return self._sub_type

    @sub_type.setter
    def sub_type(self, sub_type):
        """
        Sets the sub_type of this VMCCapacityThresholdBreachEvent.
        Event sub-type.

        :param sub_type: The sub_type of this VMCCapacityThresholdBreachEvent.
        :type: str
        """

        self._sub_type = sub_type

    @property
    def alert_entity_type(self):
        """
        Gets the alert_entity_type of this VMCCapacityThresholdBreachEvent.
        The entity type due to which the alert is raised.

        :return: The alert_entity_type of this VMCCapacityThresholdBreachEvent.
        :rtype: EntityType
        """
        return self._alert_entity_type

    @alert_entity_type.setter
    def alert_entity_type(self, alert_entity_type):
        """
        Sets the alert_entity_type of this VMCCapacityThresholdBreachEvent.
        The entity type due to which the alert is raised.

        :param alert_entity_type: The alert_entity_type of this VMCCapacityThresholdBreachEvent.
        :type: EntityType
        """

        self._alert_entity_type = alert_entity_type

    @property
    def entity_count(self):
        """
        Gets the entity_count of this VMCCapacityThresholdBreachEvent.
        The count of entities at which the alert is raised.

        :return: The entity_count of this VMCCapacityThresholdBreachEvent.
        :rtype: int
        """
        return self._entity_count

    @entity_count.setter
    def entity_count(self, entity_count):
        """
        Sets the entity_count of this VMCCapacityThresholdBreachEvent.
        The count of entities at which the alert is raised.

        :param entity_count: The entity_count of this VMCCapacityThresholdBreachEvent.
        :type: int
        """

        self._entity_count = entity_count

    @property
    def sddc_id(self):
        """
        Gets the sddc_id of this VMCCapacityThresholdBreachEvent.
        The SDDC ID of the VMC SDDC for which the alert is raised.

        :return: The sddc_id of this VMCCapacityThresholdBreachEvent.
        :rtype: str
        """
        return self._sddc_id

    @sddc_id.setter
    def sddc_id(self, sddc_id):
        """
        Sets the sddc_id of this VMCCapacityThresholdBreachEvent.
        The SDDC ID of the VMC SDDC for which the alert is raised.

        :param sddc_id: The sddc_id of this VMCCapacityThresholdBreachEvent.
        :type: str
        """

        self._sddc_id = sddc_id

    @property
    def org_id(self):
        """
        Gets the org_id of this VMCCapacityThresholdBreachEvent.
        The ORG ID of the VMC ORG to which the VMC SDDC belongs.

        :return: The org_id of this VMCCapacityThresholdBreachEvent.
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """
        Sets the org_id of this VMCCapacityThresholdBreachEvent.
        The ORG ID of the VMC ORG to which the VMC SDDC belongs.

        :param org_id: The org_id of this VMCCapacityThresholdBreachEvent.
        :type: str
        """

        self._org_id = org_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, VMCCapacityThresholdBreachEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
