# coding: utf-8

"""
    VMware Aria Operations for Networks API Reference

    Operations for Networks API Reference

    OpenAPI spec version: 6.12.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.proxy_key_rotation_status import ProxyKeyRotationStatus


class TestProxyKeyRotationStatus(unittest.TestCase):
    """ ProxyKeyRotationStatus unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProxyKeyRotationStatus(self):
        """
        Test ProxyKeyRotationStatus
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.proxy_key_rotation_status.ProxyKeyRotationStatus()
        pass


if __name__ == '__main__':
    unittest.main()
