# coding: utf-8

"""
    VMware Aria Operations for Networks API Reference

    Operations for Networks API Reference

    OpenAPI spec version: 6.12.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.license_usage_enforcement import LicenseUsageEnforcement


class TestLicenseUsageEnforcement(unittest.TestCase):
    """ LicenseUsageEnforcement unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLicenseUsageEnforcement(self):
        """
        Test LicenseUsageEnforcement
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.license_usage_enforcement.LicenseUsageEnforcement()
        pass


if __name__ == '__main__':
    unittest.main()
