# coding: utf-8

"""
    VMware Aria Operations for Networks API Reference

    Operations for Networks API Reference

    OpenAPI spec version: 6.12.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.entity_inventory_batch_list import EntityInventoryBatchList


class TestEntityInventoryBatchList(unittest.TestCase):
    """ EntityInventoryBatchList unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityInventoryBatchList(self):
        """
        Test EntityInventoryBatchList
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.entity_inventory_batch_list.EntityInventoryBatchList()
        pass


if __name__ == '__main__':
    unittest.main()
