# coding: utf-8

"""
    VMware Aria Operations for Networks API Reference

    Operations for Networks API Reference

    OpenAPI spec version: 6.12.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class BulkDataSourceRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action_type': 'str',
        'data_sources': 'list[BulkDataSourceEntity]'
    }

    attribute_map = {
        'action_type': 'action_type',
        'data_sources': 'data_sources'
    }

    def __init__(self, action_type=None, data_sources=None):
        """
        BulkDataSourceRequest - a model defined in Swagger
        """

        self._action_type = None
        self._data_sources = None

        if action_type is not None:
          self.action_type = action_type
        if data_sources is not None:
          self.data_sources = data_sources

    @property
    def action_type(self):
        """
        Gets the action_type of this BulkDataSourceRequest.
        Type of Bulk Action to perform

        :return: The action_type of this BulkDataSourceRequest.
        :rtype: str
        """
        return self._action_type

    @action_type.setter
    def action_type(self, action_type):
        """
        Sets the action_type of this BulkDataSourceRequest.
        Type of Bulk Action to perform

        :param action_type: The action_type of this BulkDataSourceRequest.
        :type: str
        """

        self._action_type = action_type

    @property
    def data_sources(self):
        """
        Gets the data_sources of this BulkDataSourceRequest.

        :return: The data_sources of this BulkDataSourceRequest.
        :rtype: list[BulkDataSourceEntity]
        """
        return self._data_sources

    @data_sources.setter
    def data_sources(self, data_sources):
        """
        Sets the data_sources of this BulkDataSourceRequest.

        :param data_sources: The data_sources of this BulkDataSourceRequest.
        :type: list[BulkDataSourceEntity]
        """

        self._data_sources = data_sources

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, BulkDataSourceRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
