# coding: utf-8

"""
    VMware Aria Operations for Networks API Reference

    Operations for Networks API Reference

    OpenAPI spec version: 6.12.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NSXTRouterDevice(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_id': 'str',
        'name': 'str',
        'entity_type': 'EntityType',
        'vendor_id': 'str',
        'manager': 'Reference',
        'tag_keys': 'list[str]',
        'tag_key_values': 'list[str]',
        'tag_values': 'list[str]'
    }

    attribute_map = {
        'entity_id': 'entity_id',
        'name': 'name',
        'entity_type': 'entity_type',
        'vendor_id': 'vendor_id',
        'manager': 'manager',
        'tag_keys': 'tag_keys',
        'tag_key_values': 'tag_key_values',
        'tag_values': 'tag_values'
    }

    def __init__(self, entity_id=None, name=None, entity_type=None, vendor_id=None, manager=None, tag_keys=None, tag_key_values=None, tag_values=None):
        """
        NSXTRouterDevice - a model defined in Swagger
        """

        self._entity_id = None
        self._name = None
        self._entity_type = None
        self._vendor_id = None
        self._manager = None
        self._tag_keys = None
        self._tag_key_values = None
        self._tag_values = None

        if entity_id is not None:
          self.entity_id = entity_id
        if name is not None:
          self.name = name
        if entity_type is not None:
          self.entity_type = entity_type
        if vendor_id is not None:
          self.vendor_id = vendor_id
        if manager is not None:
          self.manager = manager
        if tag_keys is not None:
          self.tag_keys = tag_keys
        if tag_key_values is not None:
          self.tag_key_values = tag_key_values
        if tag_values is not None:
          self.tag_values = tag_values

    @property
    def entity_id(self):
        """
        Gets the entity_id of this NSXTRouterDevice.
        Entity ID that can be references in detail API calls

        :return: The entity_id of this NSXTRouterDevice.
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """
        Sets the entity_id of this NSXTRouterDevice.
        Entity ID that can be references in detail API calls

        :param entity_id: The entity_id of this NSXTRouterDevice.
        :type: str
        """

        self._entity_id = entity_id

    @property
    def name(self):
        """
        Gets the name of this NSXTRouterDevice.
        Name of the object

        :return: The name of this NSXTRouterDevice.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this NSXTRouterDevice.
        Name of the object

        :param name: The name of this NSXTRouterDevice.
        :type: str
        """

        self._name = name

    @property
    def entity_type(self):
        """
        Gets the entity_type of this NSXTRouterDevice.

        :return: The entity_type of this NSXTRouterDevice.
        :rtype: EntityType
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """
        Sets the entity_type of this NSXTRouterDevice.

        :param entity_type: The entity_type of this NSXTRouterDevice.
        :type: EntityType
        """

        self._entity_type = entity_type

    @property
    def vendor_id(self):
        """
        Gets the vendor_id of this NSXTRouterDevice.

        :return: The vendor_id of this NSXTRouterDevice.
        :rtype: str
        """
        return self._vendor_id

    @vendor_id.setter
    def vendor_id(self, vendor_id):
        """
        Sets the vendor_id of this NSXTRouterDevice.

        :param vendor_id: The vendor_id of this NSXTRouterDevice.
        :type: str
        """

        self._vendor_id = vendor_id

    @property
    def manager(self):
        """
        Gets the manager of this NSXTRouterDevice.

        :return: The manager of this NSXTRouterDevice.
        :rtype: Reference
        """
        return self._manager

    @manager.setter
    def manager(self, manager):
        """
        Sets the manager of this NSXTRouterDevice.

        :param manager: The manager of this NSXTRouterDevice.
        :type: Reference
        """

        self._manager = manager

    @property
    def tag_keys(self):
        """
        Gets the tag_keys of this NSXTRouterDevice.

        :return: The tag_keys of this NSXTRouterDevice.
        :rtype: list[str]
        """
        return self._tag_keys

    @tag_keys.setter
    def tag_keys(self, tag_keys):
        """
        Sets the tag_keys of this NSXTRouterDevice.

        :param tag_keys: The tag_keys of this NSXTRouterDevice.
        :type: list[str]
        """

        self._tag_keys = tag_keys

    @property
    def tag_key_values(self):
        """
        Gets the tag_key_values of this NSXTRouterDevice.

        :return: The tag_key_values of this NSXTRouterDevice.
        :rtype: list[str]
        """
        return self._tag_key_values

    @tag_key_values.setter
    def tag_key_values(self, tag_key_values):
        """
        Sets the tag_key_values of this NSXTRouterDevice.

        :param tag_key_values: The tag_key_values of this NSXTRouterDevice.
        :type: list[str]
        """

        self._tag_key_values = tag_key_values

    @property
    def tag_values(self):
        """
        Gets the tag_values of this NSXTRouterDevice.

        :return: The tag_values of this NSXTRouterDevice.
        :rtype: list[str]
        """
        return self._tag_values

    @tag_values.setter
    def tag_values(self, tag_values):
        """
        Sets the tag_values of this NSXTRouterDevice.

        :param tag_values: The tag_values of this NSXTRouterDevice.
        :type: list[str]
        """

        self._tag_values = tag_values

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NSXTRouterDevice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
